# site settings
title: blaue Dächer
subtitle: von Erik & Sören
email: kontakt@blauedaecher.com
description: Wir helfen dir, deine Workshops zu digitalisieren.<br /> Mit interaktiven Methoden bringen wir frischen Wind in das Lernerlebnis.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Erik Fandrich & Sören Etler
street_address: Reiherbergstr. 15 A/B
city: Potsdam
state: 
zip_code: 14476
country: 
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram: "@blauedaecher"
instagram_url: https://www.instagram.com/blauedaecher/
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
